name: painel_administrador
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.5.0
  firebase_core: ^2.13.0
  firebase_storage: ^11.2.2
  image_picker: ^0.8.7+5
  path: ^1.8.3
  js: ^0.6.7
  path_provider: ^2.0.15
 
  

dependency_overrides:
  firebase_storage_web: 3.6.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
